### ISSUE TITLE
Button not respnding 

### ISSUE THREAD

**Issue by Nicolm1878** [lemnet/VersaKodiRemote#2]
Hello,

This remote seems a great idea, however I can not get ot to respond on my Versa 2 Watch. I have everything set correctly om the Services section of Kodi 18.9. I have everything set correctly in the settings of this app with all permission toggles enabled. It shows what's playing in the watch and all the buttons displayed
 It does not respond to the presses. Can you advice anything more I need to do.  Thanks

**Comment by lemnet** [comment]
Hello,

None of the buttons works ?
Can you feel the watch vibrate when you press the screen ?

Beside, I'm running a different version of kodi. I'll have to check compatibility with 18.9

**Comment by Nicolm1878** [comment]
No I'm afraid not (no vibrations)


But it does show what is playing so it appears to be picking my Kodi up.


Thanks pal


Get Outlook for Android

**Comment by lemnet** [comment]
So I think it is not an kodi version compatibility issue.
It has to be something wrong in my code.
I quickly looked but couldn't find whats wrong.
I'll take time to look more in depth and i'll get back to you.

**Comment by Nicolm1878** [comment]
Thanks for getting back pal, best of luck as this will be a great feature for the watch👍


Get Outlook for Android

**Comment by lemnet** [comment]
I think I founded what was wrong...
Can you try this version : https://gallery.fitbit.com/details/86269fb6-37d6-4e15-a92a-fddaabe11f75 and tell me if this works.

**Comment by trocken2** [comment]
On my Versa 2 buttons vibrate but they don't work. The same in the beta version

**Comment by Nicolm1878** [comment]
Hi pal, This version seems to not work at all now for me on Versa 2 Android 11 One UI 3.0 om the phone if  that helps at all . It displays on the watch that I need to configure in the app, it already has the correct details ip, port 8080, username and password. Wako app connects fine for the remote and so does Kore remote and Yatse so it has to be the app. The version before this did connect and shown the buttons but they did not respond


Thanks 


Get Outlook for Android 


Get Outlook for Android

**Comment by lemnet** [comment]
@trocken2 I opened a new issue.

@Nicolm1878 In the beta version i did not change anything related to the connection... I just removed a check condition. So I really don't understand what is wrong...

**Comment by Nicolm1878** [comment]
It's strange,.I just can not get this to work now. I have uninstalled the app and reinstalled and re-sync the watch. It just keeps telling me to configure the app when it is already configured. Its not Kodi 18.9 as other remote services work. It has to be something in that Beta . Thanks

**Comment by Nicolm1878** [comment]
A further update, I reset the watch to factory settings, now its back to the way it was when I first reported. Shows what's playing, buttons vibrate but receive no response.

Thanks

**Comment by lemnet** [comment]
I though that the watch didn't vibrate when you first reported an issue ?
Still the same question : none of the buttons works ? not even the sound ?
(I'll check kodi compatibility issues, probably next week)

**Comment by lemnet** [comment]
I checked kodi compatibility and it doesn't work with 18.9.
I close this issue since another one is opened for this particular issue : #4
