### ISSUE TITLE
Kodi version compatibility

### ISSUE THREAD

**Issue by lemnet** [lemnet/VersaKodiRemote#4]
On my Versa 2 buttons vibrate but they don't work. The same in the beta version

_Originally posted by @trocken2 in https://github.com/lemnet/VersaKodiRemote/issues/2#issuecomment-758196515_

**Comment by lemnet** [comment]
I think this is a kodi version compatibility issue.
None of the buttons works ? Not even the sound control ?

**Comment by trocken2** [comment]
Hi, any button didn't responding and only vibrate. I use Kodi 18.9 on Raspberry pi 4B with Libreelec OS

**Comment by lemnet** [comment]
OK, I finally tried kodi 18.9 and indeed, no button is responding.
I'll look at the api documentation and will make it work with 18.9.

**Comment by lemnet** [comment]
New version of kodi require POST request. I'll try to fix that this week.

**Comment by lemnet** [comment]
@trocken2 @Nicolm1878
Can you try the new beta et tell me if everything et working properly.
https://gallery.fitbit.com/details/86269fb6-37d6-4e15-a92a-fddaabe11f75

**Comment by trocken2** [comment]
This version is already working!

**Comment by lemnet** [comment]
Good to hear that... Thank's
I'll run a few more tests and will push it to the public version.

**Comment by Nicolm1878** [comment]
It is working this new Beta but I seem to have a delay about 2 or 3 secs after pressing, I'm not running the default Estuary skin though but rather Emby. I will try it on the default skin and let you know. Thanks


Get Outlook for Android

**Comment by lemnet** [comment]
> I seem to have a delay about 2 or 3 secs after pressing

Everything goes thru the phone... So you tap your watch and then the watch ask the phone to ask Kodi to do something. The info on the screen (playing and sound/mute) are refreshed every second.

**Comment by lemnet** [comment]
So beside that delay, this issue seems to be finally closed.
